---

- name: Build the websites on the local host
  hosts: localhost
  tags: build-sites
  tasks:
    - name: Create the websites folders
      ansible.builtin.file:
        path: "./websites/{{ item }}/contents"
        state: directory
      loop:
        - assessyoursecurity.com
        - bloodbankhub.com
        - fabioscagliola.com
        - laurabernasconi.com
        - notforprof.it
        - nothence.com
        - pmmv.nothence.com
        - step.fabioscagliola.com
        - thecodetailors.com
        - thesoftwaretailors.com

    - name: Copy the .crt files
      ansible.builtin.copy:
        src: "~/Library/CloudStorage/OneDrive-TheCodeTailorsSL/Data/certificates/{{ item }}/{{ item }}.crt"
        dest: "./websites/{{ item }}"
      loop:
        - assessyoursecurity.com
        - bloodbankhub.com
        - fabioscagliola.com
        - laurabernasconi.com
        - notforprof.it
        - nothence.com
        - thecodetailors.com
        - thesoftwaretailors.com

    - name: Copy the .key files
      ansible.builtin.copy:
        src: "~/Library/CloudStorage/OneDrive-TheCodeTailorsSL/Data/certificates/{{ item }}/{{ item }}.key"
        dest: "./websites/{{ item }}"
      loop:
        - assessyoursecurity.com
        - bloodbankhub.com
        - fabioscagliola.com
        - laurabernasconi.com
        - notforprof.it
        - nothence.com
        - thecodetailors.com
        - thesoftwaretailors.com

    - name: Create a temporary folder
      ansible.builtin.file:
        path: /tmp/my-websites-dock
        state: directory

    - name: Clone the repos to the temporary folder
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "/tmp/my-websites-dock/{{ item.dest }}"
      loop:
        - repo: git@ssh.dev.azure.com:v3/TheSoftwareTailors/Assess%20Your%20Security/Assess%20Your%20Security
          dest: assessyoursecurity.com
        - repo: git@ssh.dev.azure.com:v3/TheSoftwareTailors/Blood%20Bank%20Hub/Blood%20Bank%20Hub
          dest: bloodbankhub.com
        - repo: git@github.com:fabioscagliola/my-site-and-blog.git
          dest: fabioscagliola.com
        - repo: git@github.com:fabioscagliola/bernie.git
          dest: laurabernasconi.com
        - repo: git@ssh.dev.azure.com:v3/TheSoftwareTailors/Not%20For%20Prof.it/Not%20For%20Prof.it
          dest: notforprof.it
        - repo: git@github.com:fabioscagliola/Nothence.git
          dest: nothence.com
        - repo: git@github.com:fabioscagliola/pmmv.git
          dest: pmmv.nothence.com
        - repo: git@github.com:fabioscagliola/Step.git
          dest: step.fabioscagliola.com
        - repo: git@github.com:fabioscagliola/TheCodeTailors.git
          dest: thecodetailors.com
        - repo: git@ssh.dev.azure.com:v3/TheSoftwareTailors/Website/Website
          dest: thesoftwaretailors.com

    - name: Build the websites made with Hugo
      command: hugo build -F
      args:
        chdir: "{{ item }}"
      loop:
        - /tmp/my-websites-dock/fabioscagliola.com/fabioscagliola
        - /tmp/my-websites-dock/laurabernasconi.com/website
        - /tmp/my-websites-dock/nothence.com/nothence

    - name: Copy the contents of the websites from the temporary folder
      ansible.builtin.copy:
        src: "{{ item.source }}/"
        dest: "./websites/{{ item.target }}/contents"
      loop:
        - source: /tmp/my-websites-dock/assessyoursecurity.com/AssessYourSecuritySite
          target: assessyoursecurity.com
        - source: /tmp/my-websites-dock/bloodbankhub.com/BloodBankHubSite
          target: bloodbankhub.com
        - source: /tmp/my-websites-dock/fabioscagliola.com/fabioscagliola/public
          target: fabioscagliola.com
        - source: /tmp/my-websites-dock/laurabernasconi.com/website/public
          target: laurabernasconi.com
        - source: /tmp/my-websites-dock/notforprof.it/NotForProfSite
          target: notforprof.it
        - source: /tmp/my-websites-dock/nothence.com/nothence/public
          target: nothence.com
        - source: /tmp/my-websites-dock/pmmv.nothence.com/contents
          target: pmmv.nothence.com
        - source: /tmp/my-websites-dock/step.fabioscagliola.com/src
          target: step.fabioscagliola.com
        - source: /tmp/my-websites-dock/thecodetailors.com/site
          target: thecodetailors.com
        - source: /tmp/my-websites-dock/thesoftwaretailors.com/TheSoftwareTailorsSite
          target: thesoftwaretailors.com

    - name: Compress the websites folders
      ansible.builtin.archive:
        path: ./websites
        dest: ./websites.tar.gz

- name: Deploy the websites to the remote host
  hosts: my_websites_dock_001
  tags: copy-websites
  tasks:
    - name: Delete the temporary folder
      ansible.builtin.file:
        path: /tmp/my-websites-dock
        state: absent

    - name: Create a temporary folder
      ansible.builtin.file:
        path: /tmp/my-websites-dock/websites
        state: directory

    - name: Upload the files required to build the image
      ansible.builtin.copy:
        src: "./{{ item }}"
        dest: "/tmp/my-websites-dock/{{ item }}"
      loop:
        - Dockerfile
        - nginx.conf
        - websites.tar.gz

    - name: Extract the compressed websites folder
      ansible.builtin.unarchive:
        src: /tmp/my-websites-dock/websites.tar.gz
        dest: /tmp/my-websites-dock
        remote_src: yes

- name: Build the image
  hosts: my_websites_dock_001
  tags: build-image
  tasks:
    - name: Build the image
      community.docker.docker_image:
        build:
          path: /tmp/my-websites-dock
          nocache: true
        force_source: true
        name: my-websites-dock
        source: build

- name: Restart the container
  hosts: my_websites_dock_001
  tags: restart-container
  tasks:
    - name: Restart the container
      community.docker.docker_container:
        image: my-websites-dock
        name: my-websites-dock
        ports:
          - "80:80"
          - "443:443"
        restart: true
        restart_policy: unless-stopped
        state: started

- name: Cleanup the local host
  hosts: localhost
  tags: cleanup-local
  tasks:
    - name: Delete the websites folder
      ansible.builtin.file:
        path: ./websites
        state: absent

    - name: Delete the compressed websites folder
      ansible.builtin.file:
        path: ./websites.tar.gz
        state: absent

    - name: Delete the temporary folder
      ansible.builtin.file:
        path: /tmp/my-websites-dock
        state: absent

