---

- name: Build the websites
  hosts: localhost
  tags: build-sites
  tasks:
    - name: Create the websites' folders
      ansible.builtin.file:
        path: './websites/{{ item }}/contents'
        state: directory
      loop:
        - assessyoursecurity.com
        - bloodbankhub.com
        - fabioscagliola.com
        - laurabernasconi.com
        - notforprof.it
        - nothence.com
        - pmmv.nothence.com
        - step.fabioscagliola.com
        - thecodetailors.com
        - thesoftwaretailors.com

    - name: Copy the .crt files
      ansible.builtin.copy:
        src: '/home/fabioscagliola/Downloads/certificates/{{ item }}/{{ item }}.crt'
        dest: './websites/{{ item }}'
      loop:
        - assessyoursecurity.com
        - bloodbankhub.com
        - fabioscagliola.com
        - laurabernasconi.com
        - notforprof.it
        - nothence.com
        - thecodetailors.com
        - thesoftwaretailors.com

    - name: Copy the .key files
      ansible.builtin.copy:
        src: '/home/fabioscagliola/Downloads/certificates/{{ item }}/{{ item }}.key'
        dest: './websites/{{ item }}'
      loop:
        - assessyoursecurity.com
        - bloodbankhub.com
        - fabioscagliola.com
        - laurabernasconi.com
        - notforprof.it
        - nothence.com
        - thecodetailors.com
        - thesoftwaretailors.com

    - name: Create a temporary folder
      ansible.builtin.file:
        path: /tmp/my-websites-dock
        state: directory

    - name: Clone the repos
      ansible.builtin.git:
        repo: '{{ item.repo }}'
        dest: '/tmp/my-websites-dock/{{ item.dest }}'
      loop:
        - repo: git@ssh.dev.azure.com:v3/TheSoftwareTailors/Assess%20Your%20Security/Assess%20Your%20Security
          dest: assessyoursecurity.com
        - repo: git@ssh.dev.azure.com:v3/TheSoftwareTailors/Blood%20Bank%20Hub/Blood%20Bank%20Hub
          dest: bloodbankhub.com
        - repo: git@github.com:fabioscagliola/my-site-and-blog.git
          dest: fabioscagliola.com
        - repo: git@github.com:fabioscagliola/bernie.git
          dest: laurabernasconi.com
        - repo: git@ssh.dev.azure.com:v3/TheSoftwareTailors/Not%20For%20Prof.it/Not%20For%20Prof.it
          dest: notforprof.it
        - repo: git@github.com:fabioscagliola/Nothence.git
          dest: nothence.com
        - repo: git@github.com:fabioscagliola/pmmv.git
          dest: pmmv.nothence.com
        - repo: git@github.com:fabioscagliola/Step.git
          dest: step.fabioscagliola.com
        - repo: git@github.com:fabioscagliola/TheCodeTailors.git
          dest: thecodetailors.com
        - repo: git@ssh.dev.azure.com:v3/TheSoftwareTailors/Website/Website
          dest: thesoftwaretailors.com

    - name: Delete the public folders of the websites made with Hugo
      ansible.builtin.file:
        path: '{{ item }}/public'
        state: absent
      loop:
        - /tmp/my-websites-dock/fabioscagliola.com/fabioscagliola
        - /tmp/my-websites-dock/laurabernasconi.com/website
        - /tmp/my-websites-dock/nothence.com/nothence

    - name: Build the websites made with Hugo
      command: hugo
      args:
        chdir: '{{ item }}'
      loop:
        - /tmp/my-websites-dock/fabioscagliola.com/fabioscagliola
        - /tmp/my-websites-dock/laurabernasconi.com/website
        - /tmp/my-websites-dock/nothence.com/nothence

    - name: Copy the contents of the websites
      ansible.builtin.copy:
        src: '{{ item.source }}/'
        dest: './websites/{{ item.target }}/contents'
      loop:
        - source: /tmp/my-websites-dock/assessyoursecurity.com/AssessYourSecuritySite
          target: assessyoursecurity.com
        - source: /tmp/my-websites-dock/bloodbankhub.com/BloodBankHubSite
          target: bloodbankhub.com
        - source: /tmp/my-websites-dock/fabioscagliola.com/fabioscagliola/public
          target: fabioscagliola.com
        - source: /tmp/my-websites-dock/laurabernasconi.com/website/public
          target: laurabernasconi.com
        - source: /tmp/my-websites-dock/notforprof.it/NotForProfSite
          target: notforprof.it
        - source: /tmp/my-websites-dock/nothence.com/nothence/public
          target: nothence.com
        - source: /tmp/my-websites-dock/pmmv.nothence.com/contents
          target: pmmv.nothence.com
        - source: /tmp/my-websites-dock/step.fabioscagliola.com/src
          target: step.fabioscagliola.com
        - source: /tmp/my-websites-dock/thecodetailors.com/site
          target: thecodetailors.com
        - source: /tmp/my-websites-dock/thesoftwaretailors.com/TheSoftwareTailorsSite
          target: thesoftwaretailors.com

- name: Build the image
  hosts: localhost
  tags: build-image
  tasks:
    - name: Build the image
      community.docker.docker_image:
        archive_path: /tmp/my-websites-dock/my-websites-dock.tar
        build:
          path: .
          platform: linux/amd64
          nocache: true
        force_source: true
        name: my-websites-dock
        source: build

    - name: Compress the image
      community.general.archive:
        path: /tmp/my-websites-dock/my-websites-dock.tar

- name: Deploy the container
  become: true
  hosts: my_websites_dock
  tags: deploy
  tasks:
    - name: Stop the container
      community.docker.docker_container:
        image: my-websites-dock
        name: my-websites-dock
        state: stopped

    - name: Prune the containers
      command: docker container prune -f

    - name: Prune the images
      command: docker image prune -a -f

    - name: Upload the image to the server
      ansible.builtin.copy:
        src: /tmp/my-websites-dock/my-websites-dock.tar.gz
        dest: /data/my-websites-dock.tar.gz

    - name: Extract the image
      ansible.builtin.command: gzip -d /data/my-websites-dock.tar.gz

    - name: Load the image
      community.docker.docker_image:
        load_path: /data/my-websites-dock.tar
        name: my-websites-dock
        source: load

    - name: Delete the image
      ansible.builtin.file:
        path: /data/my-websites-dock.tar
        state: absent

    - name: Start the container
      community.docker.docker_container:
        image: my-websites-dock
        name: my-websites-dock
        ports:
          - "80:80"
          - "443:443"
        restart_policy: unless-stopped
        state: started

- name: Cleanup the local environment
  hosts: localhost
  tags: cleanup
  tasks:
    - name: Delete the contents folders
      ansible.builtin.file:
        path: ./websites
        state: absent

    - name: Delete the temporary folder
      ansible.builtin.file:
        path: /tmp/my-websites-dock
        state: absent

    - name: Delete the images
      community.docker.docker_image:
        name: '{{ item }}'
        state: absent
      loop:
        - my-websites-dock
        - nginx

